### ISSUE TITLE
debpackage.py missing

### ISSUE THREAD

**Issue by tim-gromeyer** [clckwrkbdgr/libchthon#1]
Hello, i would like to try your html2markdown tool. It depends on this library which i need to install. Unfortunately i get following error while running `make deb`:

```
/bin/sh: 1: debpackage.py: not found
make: *** [Makefile:37: libchthon2_0.5.1_amd64.deb] Fehler 127
```

I cant find the file anywhere, please help.

**Comment by clckwrkbdgr** [comment]
Sorry, I hadn't touch this project in ages, completely forgot about this external dependency.
This is from my personal dotfiles: <https://github.com/clckwrkbdgr/dotfiles/blob/master/bin/debpackage.py>
I will try to make build chain more user-friendly when I have time.
In the mean time, you can just download this script, make it executable and put somewhere in the `$PATH` (it requires only `click` package, `pip install click`).
